import React from "react"
import "tailwindcss/tailwind.css";
import NavBar from "@/app/components/nav-bar"

export const metadata = {
    title: "Next App",
    description: "Generated by create-next-app"
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html>
        <body>
        <NavBar/>
        {children}
        </body>
        </html>
    )
}